# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de675de4b23f302c9777d46d4c0373dd11e9a9f0072c8a753b5560947e4f4c4e6b07466837eceaa7862a514018d188fe2b8b595a75e47dfbce60662ccc09a26

test:
  secret_key_base: 99cafc6e091a2ccdc7b2f2784561d76959281f430ebe402f6ab677322393ad0f1c091268bed169dafe06c2865fc59775537c5e59da79e418dd25517a9469fb24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
